import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log(session);
  if (!session) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen">
          <aside className="bg-blue-100 w-48 p-4">
            <div className="rounded-full overflow-hidden w-24 mx-auto">
              <Image
                alt="profile image"
                src={session.user.image}
                height={256}
                width={256}
              />
            </div>
            <nav className="flex flex-col text-center mt-16">
              <Link href={"/account"}>Settings</Link>
              <Link href={"/analytics"}>Analytics</Link>
            </nav>
          </aside>
          <div className="p-6 max-w-4xl mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
