import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import { headers } from "next/headers";
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";
import { Page } from "@/models/Page";
import mongoose from "mongoose";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faBars, faLink } from "@fortawesome/free-solid-svg-icons";
import Link from "next/link";

const inter = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children, ...rest }) {
  const headerList = headers();
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }
  mongoose.connect(process.env.MONGODB_URI);
  const page = await Page.findOne({ owner: session.user.email });

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className="md:flex min-h-screen">
          <label
            htmlFor="navCB"
            className="cursor-pointer md:hidden ml-8 mt-4 inline-flex shadow p-4 rounded md bg-white items-center gap-2"
          >
            <FontAwesomeIcon icon={faBars} />
            <span>Menu</span>
          </label>
          <input id="navCB" type="checkbox" className="hidden" />
          <label
            htmlFor="navCB"
            className="hidden backdrop fixed inset-0 bg-black/80 z-10"
          ></label>
          <aside className=" bg-white w-48 p-4 pt-6 shadow-md fixed md:static -left-48 top-0 bottom-0 z-20 transition-all">
            <div className="sticky top-0 pt-2">
              <div className="rounded-full overflow-hidden aspect-square w-24 mx-auto">
                <Image
                  src={session.user.image}
                  width={256}
                  height={256}
                  alt={"avatar"}
                />
              </div>
              <div>
                {page && (
                  <Link
                    target="_blank"
                    href={"/" + page.uri}
                    className=" text-center mt-4 flex gap-1 items-center justify-center"
                  >
                    <FontAwesomeIcon
                      size="lg"
                      className="text-blue-500"
                      icon={faLink}
                    />
                    <span className="text-lg text-gray-500">/</span>
                    <span className="font-bold ">{page.uri}</span>
                  </Link>
                )}
              </div>

              <div className="text-center">
                <AppSidebar />
              </div>
            </div>
          </aside>
          <div className="grow">{children}</div>
        </main>
      </body>
    </html>
  );
}
