import { Lato } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";
import Image from "next/image";
import { headers } from "next/headers";
import AppSidebar from "@/components/layout/AppSidebar";
import { Toaster } from "react-hot-toast";

const inter = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children, ...rest }) {
  const headerList = headers();
  const url = headerList.get("");
  console.log(url);
  const session = await getServerSession(authOptions);

  if (!session) {
    return redirect("/");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <main className="flex min-h-screen">
          <aside className="bg-white w-48 p-4 shadow-md">
            <div className="rounded-full overflow-hidden w-24 mx-auto">
              <Image
                alt="profile image"
                src={session.user.image}
                height={256}
                width={256}
              />
            </div>
            <div className="text-center">
              <AppSidebar />
            </div>
          </aside>
          <div className="grow">
            <div className="bg-white m-8 p-4 shadow ">{children}</div>
          </div>
        </main>
      </body>
    </html>
  );
}
